# Generated by Django 3.0.8 on 2020-07-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200708_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='preferred_stylist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Employee'),
        ),
    ]
